name: JavaScript Runtime Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run once a month to track performance changes over time
    - cron: '0 0 1 * *'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run benchmarks
      run: npm run benchmark
      
    - name: Update README with benchmark results
      run: |
        # Get benchmark results section from benchmark-results.md
        RESULTS=$(cat benchmark-results.md)
        
        # Update timestamp in README
        TODAY=$(date +"%m/%d/%Y, %I:%M:%S %p")
        sed -i "s/Benchmark run on .*/Benchmark run on $TODAY/" README.md
        
        # Commit and push changes if there are any
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        git add README.md benchmark-results.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update benchmark results [skip ci]"
        
        # Only push if on main branch
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          git push
        fi